[package]
name = "jemalloc-v05-sallocx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jemallocator = "0.5.0"
jemalloc-sys = "0.5.0"
jemalloc-common = { path = "../jemalloc-common" }

[workspace]
